apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-app-config
  namespace: default
data:
  WEATHER_API_BASE_URL: "https://api.openweathermap.org/data/2.5/weather"
  WEATHER_API_UNITS: "metric"
  SERVER_PORT: "8080"
